### ISSUE TITLE
1.12 testing checklist

### ISSUE THREAD

**Issue by RoyCurtis** [Gamealition/Survival-Skripts#11]
This is an exhaustive checklist of all features this Skript collection provides. Each will be tested in PaperSpigot 1.12 on our public beta server, to ensure all is working as intended.

(Issue is WIP)

# General

_Server-wide handlers for events and commands, including global functions used by other scripts_

## Commands

- [ ] `/spawn` takes player to Overworld spawn
- [ ] `/servertime` shows server time
- [ ] `/links` and `/www` show list of clickable links
- [ ] `/modreq` aliases to `/ticket new` for players only
- [ ] `/modreq` correctly errors on no argument given
- [ ] `/broadcast-irc` broadcasts to both server and IRC for moderators only
- [ ] `/fixtoggle` reloads SignShop with a cooldown for approved only
- [ ] `//replacestair` replaces selected stair blocks with different type for WorldEdit users only
- [ ] `/dmap-enable` toggles map for given world for admins only
- [ ] `/dynmap-here` gives player a clickable Dynmap URL of location
- [ ] `/ride` attaches player A to B for moderators only
- [ ] `/gaybrush` attaches a special WorldEdit brush
- [ ] `/item-destroy` destroys held item for moderators only
- [ ] `/item-damage` damages held item for moderators only
- [ ] `/item-rename` renames held item for moderators only
- [ ] `/item-lore` sets 1st line of held item's lore for moderators only
- [ ] `/tea` and `/coffee` give respective skulls to self or target for moderators only
- [ ] `/isbanned` checks if player is banned
- [ ] `/age` checks recorded server age of offline player
- [ ] `/clearhistory` clears internal age data for player
- [ ] `/stoplag` and `/reload` are blocked from executing
- [ ] `/kit`, `/rtp`, `/wild`, `/vote` and `/tpa` give helpful messages for players only
- ~~`/nearby-entities` shows nearby entities for players only~~
- ~~`/entity-rundown` shows entity count around all players~~
- [ ] `/arm-armorstands` replaces armor stands in inventory with armed ones for approved only
- [ ] `/login` autobans for certain Wurst passwords, else kicks for attempted OP

## Events

- [ ] Daytime prolonged by going back 4 seconds every 8 passed
- [ ] Horse/zombie horse/skelly horse/donkey/mule/llama suffocation is blocked
- [ ] Wolf and cat damage triggers alert
- [ ] Trap horses in overworld are killed when triggered
- [ ] Shift-right click mob riding for ops only
- [ ] Mob spawner changing by spawn eggs blocked
- [ ] Items dropped in creative mode are marked as such
- [ ] Placing chests and trapped chest for first time shows tutorial
- [ ] Blocks nether portal use in creative worlds by redirecting to world's spawn instead
- [ ] Blocks bed use in creative worlds
- [ ] Override of Multiverse set spawn to use anchor system instead
- [ ] Override of Multiverse spawn teleport to use anchor system instead
- [ ] Auto-kick of non-admin players attempting to use `/op`
- [ ] PRISM purge at 6 AM
- [ ] Daily restart at 8 AM, with save pre-stop and warning messages 5 and 1 minutes prior
- [ ] Track player names and UUID on login
- [ ] Welcome broadcast for new players

# Approval

## Ranks

- [ ] Automatic approval for `newbie` and `untrusted` rank players
- [ ] Greeting messages for `default` and `newbie` ranks
- [ ] `/approve-info` checks approval stats, age, isbanned and flatland approval
- [ ] `/approve-me` takes player to newbie island and gives instruction for unapproveds only
- [ ] `/approve-newbie` places target in `newbie` rank except if >= tier
- [ ] `/approve-untrusted` places target in `untrusted` rank except if >= tier
- [ ] `/approve` places target in `player` rank except if >= tier
- [ ] `/unapprove` places target in `default` rank
- [ ] `/approve-newbie` refuses if target is DERPI'd
- [ ] `/approve-untrusted` refuses if target is DERPI'd
- [ ] `/approve` refuses if target is DERPI'd
- [ ] `/unapprove` refuses if target is DERPI'd
- [ ] Each approve command plays sound and broadcast to world

## Newbie island

- [ ] Correct answer tracking
- [ ] Wrong answer messages
- [ ] Auto-ban on max. wrong answers
- [ ] Auto-ban on skipping sections by cheating

## Protection

_For prevention of events by `newbie`, these must only prevent outside of resource worlds_

- [ ] Screen, chat and console messages on prevention
- [ ] Prevent item pickup for `default`
- [ ] Prevent hunger level change for `default`
- [ ] Prevent block breaking for `default` and `newbie`
- [ ] Prevent crafting for `default` and `newbie`
- [ ] Prevent block placing for `default` and `newbie`
- [ ] Prevent interact except for door, sign, stone buttons or pressure plates for `default` and `newbie`
- [ ] Prevent vehicle destroy for `default` and `newbie`
- [ ] Prevent entity hurt/kill for `default` and `newbie`

# Blacklist

- [ ] Prevent placement for lava for non-moderators or those without `gamealition.lava`
- [ ] Prevent crafting of TNT or TNT minecarts

# Buildathon

- [ ] `/buildathon-ticket` adds player to buildathon group and shows message for console only
- [ ] `/buildathon-reset` purges buildathon group for moderators and buildathon host only

# Censor

- [ ] Filter message with trigger word
- [ ] Allow message through if repeated

# DERPI

## Commands

- [ ] `/shack` teleports to DERPI spawn for inmates only
- [ ] `/quarryinfo` to get current quarry status of inmate for moderators only
- [ ] `/quarryinfo` shows if offline target is queued for quarry or release
- [ ] `/quarrylog` to get log of inmate for moderators only

## Quarrying

- [ ] `/quarry` sends player to quarry with optional offset and reason for moderators only
- [ ] `/quarry` rejects if offset is more than 0
- [ ] `/quarry` queues player for quarry on join, if offline
- [ ] `/quarry` teleports inmates if they've somehow escaped DERPI
- [ ] `/quarry` rejects if player is already quarried, with `/quarry-info` fired
- [ ] Quarry is logged
- [ ] Quarrying sets player's group to inmate, takes them to DERPI world and sets money to offset
- [ ] Quarrying broadcasts to server and IRC the event with reason
- [ ] Quarrying explains to new inmate what is going on with commands and help
- [ ] Upon quarry, inmate is healed, has DERPI inventory cleared and is given a wooden pickaxe

## Unquarrying

- [ ] `/unquarry` removes inmate from quarry for moderators only
- [ ] `/unquarry` queues inmate for unquarry on join, if offline
- [ ] `/unquarry` removes queued quarry for player, if offline
- [ ] `/unquarry` removes queued release for player, if offline and previously queued
- [ ] `/unquarry` rejects if inmate is not quarried
- [ ] Unquarry is logged
- [ ] Unquarrying deletes internal non-log quarry data
- [ ] Unquarrying sets inmate's group to default
- [ ] Unquarrying teleports inmate to newbie island
- [ ] Unquarrying broadcasts to server and IRC the event
- [ ] Unquarrying explains to player about newbie island and approval process repeat

## Signs

- [ ] All DERPI signs only work for inmates
- [ ] `[Freedom]` sign rejects if inmate has less than necessary amount
- [ ] `[Freedom]` sign unquarries inmate if has at least sufficient amount, removes amount
- [ ] `[Cobblestone]` sign rejects if inmate has too little cobblestone
- [ ] `[Cobblestone]` sign pays amount per certain amount of cobblestone, removes cobblestone
- [ ] `[Food]` sign rejects if inmate has too little cobblestone
- [ ] `[Food]` sign gives inmate a baked potato per certain amount of cobblestone, removes cobblestone
- [ ] `[Pickaxe]` sign gives inmate a wooden pickaxe per certain amount of cobblestone, removes cobblestone
- [ ] `[Pickaxe]` sign gives inmate a wooden pickaxe for free once per day
- [ ] `[Pickaxe]` sign rejects if inmate has too little cobblestone and already had free pickaxe

## Security

- [ ] Automatically quarry if queued via `/quarry` whilst inmate was offline
- [ ] Automatically unquarry if queued via `/unquarry` whilst inmate was offline
- [ ] Automatically teleport inmates to shack on join
- [ ] Automatically set group to `inmate` on join
- [ ] Prevent teleport to spawn
- [ ] Prevent teleport to home
- [ ] Prevent teleport to other players
- [ ] Prevent early release
- [ ] Prevent messaging
- [ ] Prevent use of non-DERPI commands
- [ ] Prevent non-DERPI players paying money to inmates with error and console message
- [ ] Prevent PvP of spectators by inmates
- [ ] Prevent PvP of inmates by spectators

## Misc

- [ ] Block death messages of inmates in chat; show on console only
- [ ] Notify inmate of conditions and explanation of DERPI on join
- [ ] Broadcast to world and IRC when inmate joins with current balance

# Flatland

- [ ] Screen, chat and console messages on unapproved player action prevention
- [ ] `/approve-flatland` approves player for flatland and notifies them
- [ ] `/unapprove-flatland` unapproves player for flatland and notifies them
- [ ] Prevent any mobs from spawning

## Protection

*These should affect all creative worlds, including `world_creative`, `world_chaos` and `world_buildathon`*

- [ ] Prevent block breaking
- [ ] Prevent block placing
- [ ] Prevent crafting
- [ ] Prevent bucket fill
- [ ] Prevent bucket empty
- [ ] Prevent (trapped) chest/hopper/trapdoor/furnace/anvil interaction
- [ ] Prevent vehicle destroy

# Moderator

- [ ] `/mod` to allow moderator to gain privileges
- [ ] `/demod` to allow moderator to disable privileges
- [ ] Above commands unusable by normal players

# Pigmen

- [ ] Broadcast message when pigmen angered in nether worlds only
- [ ] 5 minute cooldown for anger messages per world

# Ping

- [ ] `/ping` to toggle ping feature for player
- [ ] Every 2 seconds, all players with ping get title message and sound

# Portal

- [ ] `/portal` calculates correct portal coordinates relative to player's position and world

# PvP

## Commands and status

- [ ] `/clearpvp` clears PVP and laser tag data of player for admin only
- [ ] `/pvp` toggles PVP status for player rank only
- [ ] Toggling PVP for the first time triggers message and requires a repeat toggle
- [ ] Toggling PVP disables lasertag mode
- [ ] `/lasertag` toggles lasertag status for player rank only
- [ ] Toggling lasertag for the first time triggers message and requires a repeat toggle
- [ ] Toggling lasertag disables PVP mode
- [ ] Joining players still in PVP or lasertag mode are alerted

## Attack logic

- [ ] Does not fire if throwing enderpearls (bugfix)
- [ ] Does not handle if victim or attacker are in DERPI
- [ ] Reject if attacker is in lasertag and victim is not
- [ ] Show messages and play sounds to both attacker and victim of lasertag hit
- [ ] Allow hit if both attacker and victim in PvP mode
- [ ] Reject if attacker is in PvP and victim is not
- [ ] Reject if attacker is not in PvP and victim is

# Reuben

Disabled due to Skript bugs in latest versions

# Silence

- [ ] `/silence` toggles silence mode in server and +m on IRC
- [ ] Chat blocked for non-moderators during silence
- [ ] `/me` blocked for non-moderators during silence
- [ ] Blocked chat returns error message

# Sleep

- [ ] Sleep voting per-world, based on players in world and currently sleeping
- [ ] Entering bed recalculates vote
- [ ] Leaving bed recalculates vote only during night time 
- [ ] If threshold reached, advance day after 20 ticks and clear weather
- [ ] Broadcast calculation messages to world players, only if at least one player sleeping

# Clay wash

- [ ] `[WashClay]` sign replaces amount of non-mesa clay with hadrened clays
- [ ] `[WashMesaClay]` sign replaces amount of mesa clay with hardened clays
- [ ] Both signs impose configured cost and minimum amount
- [ ] Both signs refuse to work if inventory is full

# Wither

- [ ] `/revokewither` to revoke all passes from player for moderators only
- [ ] `/expirewither` to revoke hour pass from player for moderators only
- [ ] Creation of `[Wither]` signs restricted to moderators only
- [ ] Reject use of enter sign if player has neither hour or lifetime pass
- [ ] Reject and remove membership of player on use of enter sign if hour pass expired
- [ ] Allow and teleport player on use of enter sign with valid pass
- [ ] Reject use of hour pass sign if pass exists
- [ ] Reject use of hour pass sign if lifetime pass exists
- [ ] Reject use of hour pass sign if can't afford
- [ ] Allow use of hour pass sign, take money and add to region
- [ ] Reject use of lifetime pass sign if pass exists
- [ ] Reject use of lifetime pass sign if can't afford
- [ ] Allow use of lifetime pass sign, take money and add to region
