### ISSUE TITLE
1.9 testing checklist

### ISSUE THREAD

**Issue by RoyCurtis** [Gamealition/Survival-Skripts#2]
This is an exhaustive checklist of all features this Skript collection provides. Each will be tested in PaperSpigot 1.9 on our public beta server, to ensure all is working as intended.

(Issue is WIP)
# General

_Server-wide handlers for events and commands, including global functions used by other scripts_
## Commands
- [x] `/spawn` takes player to Overworld spawn
- [x] `/servertime` shows server time
- [x] `/links` and `/www` show list of clickable links
- [x] `/modreq` aliases to `/ticket new` for players only
- [x] `/broadcast-irc` broadcasts to both server and IRC for moderators only
- [x] `/fixtoggle` reloads SignShop with a cooldown for approved only
- [x] `//replacestair` replaces selected stair blocks with different type for WorldEdit users only
- [x] `/dmap-enable` toggles map for given world for admins only
- [x] `/dynmap-here` gives player a clickable Dynmap URL of location
- [x] `/ride` attaches player A to B for moderators only
- [x] `/item-rename` renames held item for moderators only
- [x] `/item-lore` sets 1st line of held item's lore for moderators only
- [x] `/tea` and `/coffee` give respective skulls to self or target for moderators only
- [x] `/isbanned` checks if player is banned
- [x] `/age` checks recorded server age of offline player
- [x] `/clearhistory` clears internal age data for player
- [x] `/stoplag` and `/reload` are blocked from executing
- [x] `/arm-armorstands` replaces armor stands in inventory with armed ones for approved only
- [x] `/login` autobans for certain Wurst passwords, else kicks for attempted OP
## Events
- [x] Daytime prolonged by going back 4 seconds every 8 passed
- [x] `[Bed]` signs teleport to player's bed, else spawn
- [x] Horse/donkey/mule suffocation is blocked
- [x] Wolf and cat damage triggers alert
- [x] Shift-right click mob riding for ops only
- [x] Mob spawner changing by spawn eggs blocked
- [x] Items dropped in creative mode are marked as such
- [x] Override of Multiverse set spawn to use anchor system instead
- [x] Override of Multiverse spawn teleport to use anchor system instead
- [x] Auto-kick of non-admin players attempting to use `/op`
- [x] PRISM purge at 6 AM
- [x] Daily restart at 8 AM, with save pre-stop and warning messages 5 and 1 minutes prior
- [x] Track player names and UUID on login
- [x] Welcome broadcast for new players
- [x] LWC tutorial upon placing a chest for first time
# Approval
## Ranks
- [x] Automatic approval for `newbie` and `untrusted` rank players
- [x] Greeting messages for `default` and `newbie` ranks
- [x] `/approve-info` checks approval stats, age, isbanned and flatland approval
- [x] `/approve-me` takes player to newbie island and gives instruction for unapproveds only
- [x] `/approve-newbie` places target in `newbie` rank except if >= tier
- [x] `/approve-untrusted` places target in `untrusted` rank except if >= tier
- [x] `/approve` places target in `player` rank except if >= tier
- [x] `/unapprove` places target in `default` rank
- [x] `/approve-newbie` refuses if target is DERPI'd
- [x] `/approve-untrusted` refuses if target is DERPI'd
- [x] `/approve` refuses if target is DERPI'd
- [x] `/unapprove` refuses if target is DERPI'd
- [x] Each approve command plays sound and broadcast to world
## Newbie island
- [x] Wrong answer messages
- [x] Auto-ban on max. wrong answers
## Protection

_For prevention of events by `newbie`, these must only prevent outside of resource worlds_
- [x] Screen, chat and console messages on prevention
- [x] Prevent item pickup for `default`
- [x] Prevent hunger level change for `default`
- [x] Prevent block breaking for `default` and `newbie`
- [x] Prevent crafting for `default` and `newbie`
- [x] Prevent block placing for `default` and `newbie`
- [x] Prevent (trapped) chest/hopper/trapdoor/furnace/anvil interaction for `default` and `newbie`
- [x] Prevent vehicle destroy for `default` and `newbie`
- [x] Prevent entity hurt/kill for `default` and `newbie`
# Censor
- [x] Filter message with trigger word
- [x] Allow message through if repeated
# DERPI
## Commands
- [x] `/shack` teleports to DERPI spawn for inmates only
- [x] `/quarryinfo` to get current quarry status of inmate for moderators only
- [x] `/quarryinfo` shows if offline target is queued for quarry or release
- [x] `/quarrylog` to get log of inmate for moderators only
## Quarrying
- [x] `/quarry` sends player to quarry with optional offset and reason for moderators only
- [x] `/quarry` rejects if offset is more than 0
- [x] `/quarry` queues player for quarry on join, if offline
- [x] `/quarry` teleports inmates if they've somehow escaped DERPI
- [x] `/quarry` rejects if player is already quarried, with `/quarry-info` fired
- [x] Quarry is logged
- [x] Quarrying sets player's group to inmate, takes them to DERPI world and sets money to offset
- [x] Quarrying broadcasts to server and IRC the event with reason
- [x] Quarrying explains to new inmate what is going on with commands and help
- [x] Upon quarry, inmate is healed, has DERPI inventory cleared and is given a wooden pickaxe
## Unquarrying
- [x] `/unquarry` removes inmate from quarry for moderators only
- [x] `/unquarry` queues inmate for unquarry on join, if offline
- [x] `/unquarry` removes queued quarry for player, if offline
- [x] `/unquarry` removes queued release for player, if offline and previously queued
- [x] `/unquarry` rejects if inmate is not quarried
- [x] Unquarry is logged
- [x] Unquarrying deletes internal non-log quarry data
- [x] Unquarrying sets inmate's group to default
- [x] Unquarrying teleports inmate to newbie island
- [x] Unquarrying broadcasts to server and IRC the event
- [x] Unquarrying explains to player about newbie island and approval process repeat
## Signs
- [x] All DERPI signs only work for inmates
- [x] `[Freedom]` sign rejects if inmate has less than necessary amount
- [x] `[Freedom]` sign unquarries inmate if has at least sufficient amount, removes amount
- [x] `[Cobblestone]` sign rejects if inmate has too little cobblestone
- [x] `[Cobblestone]` sign pays amount per certain amount of cobblestone, removes cobblestone
- [x] `[Food]` sign rejects if inmate has too little cobblestone
- [x] `[Food]` sign gives inmate a baked potato per certain amount of cobblestone, removes cobblestone
- [x] `[Pickaxe]` sign gives inmate a wooden pickaxe per certain amount of cobblestone, removes cobblestone
- [x] `[Pickaxe]` sign gives inmate a wooden pickaxe for free once per day
- [x] `[Pickaxe]` sign rejects if inmate has too little cobblestone and already had free pickaxe
## Security
- [x] Automatically quarry if queued via `/quarry` whilst inmate was offline
- [x] Automatically unquarry if queued via `/unquarry` whilst inmate was offline
- [x] Automatically teleport inmates to shack on join
- [x] Automatically set group to `inmate` on join
- [x] Prevent teleport to spawn
- [x] Prevent teleport to home
- [x] Prevent teleport to other players
- [x] Prevent early release
- [x] Prevent messaging
- [x] Prevent use of non-DERPI commands
- [x] Prevent non-DERPI players paying money to inmates with error and console message
- [x] Prevent PvP of spectators by inmates
- [x] Prevent PvP of inmates by spectators
## Misc
- [x] Block death messages of inmates in chat; show on console only
- [x] Notify inmate of conditions and explanation of DERPI on join
- [x] Broadcast to world and IRC when inmate joins with current balance
# Flatland
- [x] Screen, chat and console messages on unapproved player action prevention
- [x] `/approve-flatland` approves player for flatland and notifies them
- [x] `/unapprove-flatland` unapproves player for flatland and notifies them
## Protection
- [x] Prevent block breaking
- [x] Prevent block placing
- [x] Prevent crafting
- [x] Prevent bucket fill
- [x] Prevent bucket empty
- [x] Prevent (trapped) chest/hopper/trapdoor/furnace/anvil interaction
- [x] Prevent vehicle destroy
# Moderator
- [x] `/mod` to allow moderator to gain privileges
- [x] `/demod` to allow moderator to disable privileges
- [x] Above commands unusable by normal players
# Pigmen
- [x] Broadcast message when pigmen angered in nether worlds only
- [x] 5 minute cooldown for anger messages per world
# Ping
- [x] `/ping` to toggle ping feature for player
- [x] Every 2 seconds, all players with ping get title message and sound
# Portal
- [x] `/portal` calculates correct portal coordinates relative to player's position and world
# PvP
## Commands and status
- [x] `/clearpvp` clears PVP and laser tag data of player for admin only
- [x] `/pvp` toggles PVP status for player rank only
- [x] Toggling PVP for the first time triggers message and requires a repeat toggle
- [x] Toggling PVP disables lasertag mode
- [x] `/lasertag` toggles lasertag status for player rank only
- [x] Toggling lasertag for the first time triggers message and requires a repeat toggle
- [x] Toggling lasertag disables PVP mode
- [x] Joining players still in PVP or lasertag mode are alerted
## Attack logic
- [x] Does not fire if throwing enderpearls (bugfix)
- [x] Does not handle if victim or attacker are in DERPI
- [x] Reject if attacker is in lasertag and victim is not
- [x] Show messages and play sounds to both attacker and victim of lasertag hit
- [x] Allow hit if both attacker and victim in PvP mode
- [x] Reject if attacker is in PvP and victim is not
- [x] Reject if attacker is not in PvP and victim is
# Reuben
## Logic
- [x] Slight hop at every reaction
- [x] Noise at every reaction
- [x] Random message given to player
- [x] 1 second cooldown between interactions
## Reactions
- [x] Attacked by melee, with events cancelled
- [x] Attacked by projectile, with events cancelled
- [x] 10% interact chance whilst thundering, with lightning effect
- [x] 50% interact chance whilst player flying
- [x] 50% interact chance whilst wearing leather armor
- [x] 50% interact chance whilst player poisoned
- [x] Interacted if leashed or saddled, with events cancelled
- [x] Interacted holding pork
- [x] 75% interact chance holding meat or fish
- [x] 75% interact chance holding fruit or veg, with regen
- [x] 90% interact chance holding carrot, with regen
- [x] 50% interact chance holding carrot and stick
- [x] 50% interact chance holding apple
- [x] 50% interact chance holding wheat
- [x] 50% interact chance holding weapon, with nausea on pig
- [x] Interacted holding lighter, with fire and noise
- [x] Interacted holding TNT or firework, with explosion and upward launch
# Silence
- [x] `/silence` toggles silence mode in server and +m on IRC
- [x] Chat blocked for non-moderators during silence
- [ ] `/me` blocked for non-moderators during silence
- [x] Blocked chat returns error message
# Sleep
- [x] Sleep voting per-world, based on players in world and currently sleeping
- [x] Entering bed recalculates vote
- [x] Leaving bed recalculates vote only during night time 
- [x] If threshold reached, advance day after 20 ticks and clear weather
- [x] Broadcast calculation messages to world players, only if at least one player sleeping
# Clay wash
- [x] `[WashClay]` sign replaces amount of non-mesa clay with hadrened clays
- [x] `[WashMesaClay]` sign replaces amount of mesa clay with hardened clays
- [x] Both signs impose configured cost and minimum amount
# Wither
- [x] `/revokewither` to revoke all passes from player for moderators only
- [x] `/expirewither` to revoke hour pass from player for moderators only
- [x] Creation of `[Wither]` signs restricted to moderators only
- [x] Reject use of enter sign if player has neither hour or lifetime pass
- [x] Reject and remove membership of player on use of enter sign if hour pass expired
- [x] Allow and teleport player on use of enter sign with valid pass
- [x] Reject use of hour pass sign if pass exists
- [x] Reject use of hour pass sign if lifetime pass exists
- [x] Reject use of hour pass sign if can't afford
- [x] Allow use of hour pass sign, take money and add to region
- [x] Reject use of lifetime pass sign if pass exists
- [x] Reject use of lifetime pass sign if can't afford
- [x] Allow use of lifetime pass sign, take money and add to region

**Comment by RoyCurtis** [comment]
Closing despite "/me blocked for non-moderators during silence" ( #5 ) not being fixed.
